# Generated by Django 6.0.5 on 2026-05-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('payment', 'Pitch Booking Payment'), ('refund', 'Booking Refund'), ('withdrawal', 'Bank Withdrawal')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('processing', 'Processing'), ('failed', 'Failed')], default='completed', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
