# Generated by Django 6.0.5 on 2026-05-18 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_squad_squadmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='joined_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
