# Generated by Django 6.0.5 on 2026-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_match_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='⚽', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Ready to play!'),
        ),
        migrations.AddField(
            model_name='user',
            name='caps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='Intermediate', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Striker', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='Rookie', max_length=50),
        ),
    ]
